
services:

  one-el:
    build: .
    restart: "no"
    volumes:
      - .:/usr/src/app/
      
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 9100:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
