name: Gitea Actions Deploy
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

defaults:
  run:
    shell: bash

jobs:
  Explore-Gitea-Actions:
    steps:
      - name: List files in the repository
        run: |
          ls
